"""
Extract reusable fingerprint fields from a captured /api2/reload request
body into a JSON config file (fingerprint.json).

These fields are generated by webworker.js and are what reCAPTCHA scores on.
They can be reused for the same site key within a validity window to obtain
a higher score than the form-encoded fallback.

Usage:
    uv run python extract_fingerprint.py tests/fixtures/reload_req.bin fingerprint.json
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from proto_decode import decode  # noqa: E402


REUSABLE_FIELDS = [5, 7, 16, 20, 22, 25]
INT_FIELDS = (28, 29)


def main() -> None:
    src = Path(sys.argv[1])
    dst = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("fingerprint.json")

    data = src.read_bytes()
    entries = decode(data)

    config: dict = {}
    for field, wire, value in entries:
        if field in REUSABLE_FIELDS and wire == 2:
            config[str(field)] = value.decode("utf-8", errors="replace")
        elif field in INT_FIELDS:
            config[str(field)] = value

    config["_source"] = str(src)
    config["_note"] = (
        "Reusable fingerprint fields from a captured /api2/reload request. "
        "Generated by webworker.js. Reuse for the same site key to boost score."
    )

    dst.write_text(json.dumps(config, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"wrote {dst}")
    for k in sorted(config):
        if k.startswith("_"):
            continue
        v = config[k]
        if isinstance(v, str):
            print(f"  field {k}: {len(v)} chars  {v[:50]}...")
        else:
            print(f"  field {k}: {v}")


if __name__ == "__main__":
    main()
