"""
Generate a synthetic reCAPTCHA v3 fingerprint config.

Produces plausible motion/event data (fields 20, 25) so you don't ship
personal device data in fingerprint.json. The opaque fields (7, 16, 22)
are omitted by default because they are device-bound blobs generated by
Google's obfuscated webworker.js and cannot be synthesized meaningfully.

Without the opaque fields the score will be lower (~0.3-0.5) than with a
real captured fingerprint (~0.7-0.9). For a higher score without personal
data, run a headless browser to generate a fresh fingerprint on a clean
profile and feed the resulting reload request to extract_fingerprint.py.

Usage:
    uv run python tools/generate_fingerprint.py fingerprint.json
    uv run python tools/generate_fingerprint.py fingerprint.json --seed 42
"""
import argparse
import base64
import json
import random
import sys
from pathlib import Path

# Field 28/29: anchor-ms / execute-ms from the anchor URL (stable defaults).
ANCHOR_MS = 20000
EXECUTE_MS = 30000


def _b64(s: str) -> str:
    return base64.b64encode(s.encode("utf-8")).decode("ascii")


def gen_field_20(rng: random.Random) -> str:
    """Mouse/touch event timing array.

    Decodes to JSON like:
      [[<id>,<count>],[<id>,<count>],[<id>,<value>],null,
       [null,null,null,[4,5.75,0.0011...,15],[238,0.0588...,0.0007...,1],0,0,0],
       ["2captcha.com","static.cloudflareinsights.com","www.google.com","www.gstatic.com"],
       [1,440]]

    We synthesize a plausible shape with randomized perf-like values.
    """
    perf1 = round(rng.uniform(4.0, 7.0), 2)
    rate1 = round(rng.uniform(0.0008, 0.0015), 18)
    perf2 = round(rng.uniform(0.04, 0.07), 18)
    rate2 = round(rng.uniform(0.0005, 0.0009), 22)
    inner = [[perf1, rate1, 15], [238, perf2, rate2, 1], 0, 0, 0]
    data = [
        [[5006, 44], [64607, 1], [35837, 1]],
        None,
        [None, None, None, inner],
        ["2captcha.com", "static.cloudflareinsights.com", "www.google.com", "www.gstatic.com"],
        [1, 440],
    ]
    return _b64(json.dumps(data, separators=(",", ":")))


def gen_field_25(rng: random.Random) -> str:
    """Event sequence array. Decodes to JSON like:
        [[[<event_id>,<delta>],[<event_id>,<delta>],[<event_id>,<delta>]]]
    """
    events = []
    t = 0
    for _ in range(rng.randint(2, 5)):
        t += rng.randint(1000, 80000)
        events.append([rng.choice([5006, 64607, 35837]), t])
    return _b64(json.dumps([events], separators=(",", ":")))


def generate(seed: int | None = None) -> dict:
    rng = random.Random(seed)
    return {
        "5": str(rng.randint(-2000000000, -1000000000)),
        "20": gen_field_20(rng),
        "25": gen_field_25(rng),
        "28": ANCHOR_MS,
        "29": EXECUTE_MS,
        "_note": (
            "Synthetic fingerprint (no personal device data). "
            "Motion fields (20, 25) are randomized; opaque fields "
            "(7, 16, 22) are omitted. Score will be lower than a "
            "real captured fingerprint."
        ),
    }


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("output", help="output JSON path (e.g. fingerprint.json)")
    p.add_argument("--seed", type=int, default=None, help="random seed")
    args = p.parse_args()

    fp = generate(args.seed)
    out = Path(args.output)
    out.write_text(json.dumps(fp, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"wrote {out}")
    for k in sorted(fp):
        if k.startswith("_"):
            continue
        v = fp[k]
        vs = str(v)
        print(f"  field {k}: {vs[:60]}{'...' if len(vs) > 60 else ''}")


if __name__ == "__main__":
    sys.exit(main() or 0)
